substitutions:
  esphome_name: espnow-hub
  esphome_friendly_name: "ESPNow Hub Test"

  initial_espnow_channel: "1"
  espnow_own_address: #add your wifi mac address"
  ethernet_use_address: #add ethernet ip 
  time_on_time_cron:  '/13 * * * * *'

packages:
  espnow_common: !include espnow/espnow_common.yaml
  
esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_friendly_name}

      
logger:
  level: DEBUG # INFO

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf
    advanced:
    #   compiler_optimization: PERF
    # [06:03:34.964][W][app:174]: Chip rev >= 3.0 detected. Set minimum_chip_revision: "3.0" under esp32 > framework > advanced to reduce binary size
      minimum_chip_revision: "3.0" 
    # [06:03:34.966][W][app:201]: Bootloader supports SRAM1 as IRAM (+40KB). Set sram1_as_iram: true under esp32 > framework > advanced
      sram1_as_iram: true
                            
espnow:
  channel: ${initial_espnow_channel}
  auto_add_peer: True

  on_broadcast:
    - lambda: |-
        using namespace std;

        string s_data;
        size_t s_data_size = ESPNowHelpers::parseJSON_S(data, size, s_data);

        if (0 >= s_data_size) {
          ESP_LOGD("on_broadcast", "received 0 length message (json_data: %s)", s_data.c_str());
          return;
        }

        ESP_LOGD("on_broadcast", "json_data: %s", s_data.c_str());

        string sender = str_snprintf("%02X:%02X:%02X:%02X:%02X:%02X", 17, info.src_addr[0], info.src_addr[1], info.src_addr[2], info.src_addr[3], info.src_addr[4], info.src_addr[5]);
        string via = str_snprintf("%02X:%02X:%02X:%02X:%02X:%02X", 17, info.des_addr[0], info.des_addr[1], info.des_addr[2], info.des_addr[3], info.des_addr[4], info.des_addr[5]);
        string receiver = "${espnow_own_address}";
        double rssi = info.rx_ctrl->rssi;

        id(send_hass_event_espnow_message)->execute(s_data, sender, receiver, via, rssi);

    - lambda: |-
        char des_mac[MAC_ADDRESS_PRETTY_BUFFER_SIZE];
        char src_mac[MAC_ADDRESS_PRETTY_BUFFER_SIZE];
        char hex[256];
        ESP_LOGV("on_broadcast", "Sent to %s from %s: %s RSSI: %ddBm",
                 format_mac_addr_upper(info.des_addr, des_mac),
                 format_mac_addr_upper(info.src_addr, src_mac),
                 format_hex_pretty_to(hex, data, size),
                 info.rx_ctrl->rssi);

    - sensor.template.publish:
        id: broadcast_received
        state: !lambda |-
          if (0 < id(broadcast_received).state) {
            return 1 + (int)id(broadcast_received).state;
          } else {
            return 1;
          }

sensor:
  - platform: template
    name: Direct Received
    id: direct_received
    entity_category: diagnostic
    disabled_by_default: true
  - platform: template
    name: Broadcast Received
    id: broadcast_received
    disabled_by_default: true
    entity_category: diagnostic

api:
  
time:
  - platform: homeassistant
    id: esphome_time
    on_time:
      - cron: ${time_on_time_cron}
        then:
          - script.execute: broadcast_time

script:
  - id: broadcast_time
    then:
      - logger.log: 
          format: "Broadcasting time %d"
          args: 
            - id(esphome_time).now().timestamp
      - espnow.broadcast:
          data: !lambda |-
            CayenneLPP lpp(160);
            lpp.reset();

            lpp.addUnixTime(${espnow_sys_channel}, id(esphome_time).now().timestamp);

            uint8_t* m = lpp.getBuffer();
            std::vector<unsigned char> my_vector(
                m,
                m + lpp.getSize());
            return my_vector;

  - id: send_hass_event_espnow_message
    mode: queued
    max_runs: 99
    parameters:
      event_data: string
      sender: string
      receiver: string
      via: string
      rssi: float
    then:
      - homeassistant.event:
          event: esphome.espnow_message
          data_template:
            sender_data: '{{ sender_data }}'
            sender: '{{ from_node }}'
            receiver: '{{ receiver_node }}'
            via: '{{ via_node }}'
            rssi: '{{ rssi }}'
          variables:
            sender_data: !lambda |-
              return event_data;
            from_node: !lambda |-
              return sender;
            receiver_node: !lambda |-
              return receiver;
            via_node: !lambda |-
              return via;
            rssi: !lambda |-
              return rssi;

#############
ethernet:
  mdc_pin: 23
  mdio_pin: 18
  clk:
    pin: 17
    mode: CLK_OUT
  phy_addr: 0
  power_pin: 12
  domain: .iotl.lan
  type: LAN8720
  use_address: ${ethernet_use_address}
